{
  "comments": [
    {
      "unresolved": true,
      "key": {
        "uuid": "ebe54bf0_ef263e85",
        "filename": "ci-scripts/infra-setup/roles/rrcockpit/files/telegraf_py3/ruck_rover.py",
        "patchSetId": 3
      },
      "lineNbr": 179,
      "author": {
        "id": 671
      },
      "writtenOn": "2022-03-11T07:14:27Z",
      "side": 1,
      "message": "This broke Centos-7 train\n\n\n$rr --distro centos-7 --release train\nTraceback (most recent call last):\n  File \"/usr/lib/python3.9/site-packages/urllib3/connection.py\", line 156, in _new_conn\n    conn \u003d connection.create_connection(\n  File \"/usr/lib/python3.9/site-packages/urllib3/util/connection.py\", line 61, in create_connection\n    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):\n  File \"/usr/lib64/python3.9/socket.py\", line 954, in getaddrinfo\n    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):\nsocket.gaierror: [Errno -2] Name or service not known\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/usr/lib/python3.9/site-packages/urllib3/connectionpool.py\", line 665, in urlopen\n    httplib_response \u003d self._make_request(\n  File \"/usr/lib/python3.9/site-packages/urllib3/connectionpool.py\", line 376, in _make_request\n    self._validate_conn(conn)\n  File \"/usr/lib/python3.9/site-packages/urllib3/connectionpool.py\", line 994, in _validate_conn\n    conn.connect()\n  File \"/usr/lib/python3.9/site-packages/urllib3/connection.py\", line 300, in connect\n    conn \u003d self._new_conn()\n  File \"/usr/lib/python3.9/site-packages/urllib3/connection.py\", line 168, in _new_conn\n    raise NewConnectionError(\nurllib3.exceptions.NewConnectionError: \u003curllib3.connection.VerifiedHTTPSConnection object at 0x7f1b8aba81c0\u003e: Failed to establish a new connection: [Errno -2] Name or service not known",
      "range": {
        "startLine": 177,
        "startChar": 0,
        "endLine": 179,
        "endChar": 35
      },
      "revId": "8f394e5e2056ae83a1ac10d3f499fc1526e0b603",
      "serverId": "270e2033-b340-4cff-9539-693957ebf0e7"
    },
    {
      "unresolved": true,
      "key": {
        "uuid": "f04af517_b73eb628",
        "filename": "ci-scripts/infra-setup/roles/rrcockpit/files/telegraf_py3/ruck_rover.py",
        "patchSetId": 3
      },
      "lineNbr": 179,
      "author": {
        "id": 756
      },
      "writtenOn": "2022-03-11T14:10:16Z",
      "side": 1,
      "message": "Sandeep, obviously. I didn\u0027t know we\u0027re still taking care of c7-train.\nI\u0027ll address that shortly.\n\nSorry for that.",
      "parentUuid": "ebe54bf0_ef263e85",
      "range": {
        "startLine": 177,
        "startChar": 0,
        "endLine": 179,
        "endChar": 35
      },
      "revId": "8f394e5e2056ae83a1ac10d3f499fc1526e0b603",
      "serverId": "270e2033-b340-4cff-9539-693957ebf0e7"
    }
  ]
}