{
  "comments": [
    {
      "key": {
        "uuid": "6d22058b_4acf58bd",
        "filename": "ci-scripts/dlrnapi_promoter/dlrnapi_promoter.py",
        "patchSetId": 8
      },
      "lineNbr": 53,
      "author": {
        "id": 63
      },
      "writtenOn": "2019-11-14T18:34:30Z",
      "side": 1,
      "message": "This is the things I\u0027m most unsure about. Raising an exception will completely block the run on every hash in all the phases for a particular branch. Also, what will happend in a next rerun ? will this pass or will block again ? Maybe it\u0027s better to put just an error in the log ? Or do a lot more than this and put an inhibitor to block this and any successful runs until the situation is solved ? or a rollback ?",
      "revId": "9b4f2f5956dcdab4761e5788a8b00ce4834cd6b8",
      "serverId": "270e2033-b340-4cff-9539-693957ebf0e7",
      "unresolved": false
    }
  ]
}