{
  "comments": [
    {
      "key": {
        "uuid": "edf11b6a_12260be9",
        "filename": "ci-scripts/dlrnapi_promoter/dlrn_client.py",
        "patchSetId": 11
      },
      "lineNbr": 113,
      "author": {
        "id": 63
      },
      "writtenOn": "2020-03-12T16:14:27Z",
      "side": 1,
      "message": "this will fail to log, we need another %s here, or the second value will not be used.",
      "revId": "a3b896f051aca5037f54bbeb23a725884dafc72f",
      "serverId": "270e2033-b340-4cff-9539-693957ebf0e7",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "e9a2607d_3f44fa7b",
        "filename": "ci-scripts/dlrnapi_promoter/dlrn_client.py",
        "patchSetId": 11
      },
      "lineNbr": 113,
      "author": {
        "id": 192
      },
      "writtenOn": "2020-03-13T08:58:39Z",
      "side": 1,
      "message": "ack its cos we removed the .format ... checking\n\nand i see it in the logs too DEBUG:promoter:Fetching promotion hashes from label current-tripleo\nTraceback (most recent call last):\n  File \"/usr/lib64/python2.7/logging/__init__.py\", line 851, in emit\n    msg \u003d self.format(record)\n  File \"/usr/lib64/python2.7/logging/__init__.py\", line 724, in format\n    return fmt.format(record)\n  File \"/usr/lib64/python2.7/logging/__init__.py\", line 464, in format\n    record.message \u003d record.getMessage()\n  File \"/usr/lib64/python2.7/logging/__init__.py\", line 328, in getMessage\n    msg \u003d msg % self.args\nTypeError: not all arguments converted during string formatting\nLogged from file dlrn_client.py, line 114\n\n\nBUT why didn\u0027t it fail?",
      "parentUuid": "edf11b6a_12260be9",
      "revId": "a3b896f051aca5037f54bbeb23a725884dafc72f",
      "serverId": "270e2033-b340-4cff-9539-693957ebf0e7",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "52a1a32b_fd6df770",
        "filename": "ci-scripts/dlrnapi_promoter/test_dlrn_client_unit.py",
        "patchSetId": 11
      },
      "lineNbr": 422,
      "author": {
        "id": 63
      },
      "writtenOn": "2020-03-12T16:14:27Z",
      "side": 1,
      "message": "good",
      "revId": "a3b896f051aca5037f54bbeb23a725884dafc72f",
      "serverId": "270e2033-b340-4cff-9539-693957ebf0e7",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "08815e82_831e871a",
        "filename": "ci-scripts/dlrnapi_promoter/test_dlrn_client_unit.py",
        "patchSetId": 11
      },
      "lineNbr": 435,
      "author": {
        "id": 63
      },
      "writtenOn": "2020-03-12T16:14:27Z",
      "side": 1,
      "message": "great, reuse as much as possible, even tests will have to be maintained, and doing like this will ease the task",
      "revId": "a3b896f051aca5037f54bbeb23a725884dafc72f",
      "serverId": "270e2033-b340-4cff-9539-693957ebf0e7",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "368238f1_7778bbaa",
        "filename": "ci-scripts/dlrnapi_promoter/test_dlrn_client_unit.py",
        "patchSetId": 11
      },
      "lineNbr": 444,
      "author": {
        "id": 63
      },
      "writtenOn": "2020-03-12T16:14:27Z",
      "side": 1,
      "message": "you should add an assert to ensure that the outcome is ok. Without asserts, it\u0027s impossibile to tell if these functions actually did anything.",
      "revId": "a3b896f051aca5037f54bbeb23a725884dafc72f",
      "serverId": "270e2033-b340-4cff-9539-693957ebf0e7",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "f3a9c6b2_14e399aa",
        "filename": "ci-scripts/dlrnapi_promoter/test_dlrn_client_unit.py",
        "patchSetId": 11
      },
      "lineNbr": 488,
      "author": {
        "id": 63
      },
      "writtenOn": "2020-03-12T16:14:27Z",
      "side": 1,
      "message": "If you checked the debug calls here, you would have caught the error in logging call parameters I mentioned above.",
      "revId": "a3b896f051aca5037f54bbeb23a725884dafc72f",
      "serverId": "270e2033-b340-4cff-9539-693957ebf0e7",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "0f30db66_9e8486b6",
        "filename": "ci-scripts/dlrnapi_promoter/test_dlrn_client_unit.py",
        "patchSetId": 11
      },
      "lineNbr": 496,
      "author": {
        "id": 63
      },
      "writtenOn": "2020-03-12T16:14:27Z",
      "side": 1,
      "message": "We should assert that the warning has been called too",
      "revId": "a3b896f051aca5037f54bbeb23a725884dafc72f",
      "serverId": "270e2033-b340-4cff-9539-693957ebf0e7",
      "unresolved": false
    }
  ]
}